[package]
name = "tim"
version = "0.1.0"
authors = ["aeryz <abdullaheryz@protonmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = { version = "2.33", features = ["yaml"] }
thiserror = "1.0"
walkdir = "2"
